# Generated by Django 4.1.5 on 2023-01-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity_Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ID_REPORT", models.IntegerField(unique=True)),
                ("Titulo", models.CharField(max_length=50)),
                ("Balao", models.CharField(max_length=300)),
                ("Imagem", models.ImageField(upload_to="BD_User_Report/")),
            ],
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "N_Eleicao",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("Titulo", models.CharField(max_length=30)),
                ("Data", models.DateField()),
                ("Descricao", models.CharField(max_length=150, null=True)),
                ("Ativo", models.BooleanField()),
                ("Disponibilizar", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "Id_Academico",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("Nome", models.CharField(max_length=50)),
                ("CPF", models.IntegerField(unique=True)),
                (
                    "Genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")], max_length=1
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("Senha", models.CharField(max_length=50)),
                ("Foto", models.ImageField(upload_to="BD_User_img/")),
            ],
        ),
        migrations.CreateModel(
            name="Interaction_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Data", models.DateField()),
                (
                    "N_Eleicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.election"
                    ),
                ),
                (
                    "Usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="election",
            name="Usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Users.user"
            ),
        ),
        migrations.CreateModel(
            name="Data_Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Candidatos", models.CharField(max_length=50, unique=True)),
                ("Votos", models.IntegerField()),
                (
                    "N_Eleicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.election"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activity_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Horario", models.DateField()),
                ("Disponibilizar", models.BooleanField()),
                (
                    "Participacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.election"
                    ),
                ),
                (
                    "Report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.activity_report",
                    ),
                ),
                (
                    "Usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activity_report",
            name="Usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Users.user"
            ),
        ),
    ]
