# Generated by Django 4.1.5 on 2023-01-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Foto',
            field=models.ImageField(null=True, upload_to='BD_User_img/'),
        ),
    ]
