# Generated by Django 4.1.5 on 2023-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='BD_User_img/'),
        ),
    ]
