# Generated by Django 4.1.5 on 2023-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Id_Academico',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
