# Generated by Django 4.1.5 on 2023-01-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Foto',
            field=models.ImageField(upload_to='<django.db.models.fields.CharField>/BD_User_img/', verbose_name='Imagem do perfil'),
        ),
    ]
