# Generated by Django 4.1.5 on 2023-01-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Foto',
            field=models.ImageField(default=None, upload_to='', verbose_name='Imagem do perfil'),
        ),
    ]
