# Generated by Django 4.1.5 on 2023-01-05 10:37

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_alter_user_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagem_jpeg',
            field=stdimage.models.JPEGField(default=1, force_min_size=False, upload_to='path/to/img', variations={'full': (None, None), 'thumbnail': (100, 75)}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='Foto',
            field=models.ImageField(default=None, upload_to='BD_User_img', verbose_name='Imagem do perfil'),
        ),
    ]
