# Generated by Django 4.1.5 on 2023-01-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_user_imagem_jpeg_alter_user_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='imagem_jpeg',
            new_name='imagem',
        ),
        migrations.AlterField(
            model_name='user',
            name='Foto',
            field=models.ImageField(upload_to='BD_User_img', verbose_name='Imagem do perfil'),
        ),
    ]
