# Generated by Django 4.1.5 on 2023-01-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Foto',
            field=models.ImageField(default='<django.db.models.fields.CharField>Img_Perfil.jpg)', upload_to='BD_User_img', verbose_name='Imagem do perfil'),
        ),
    ]
