# Generated by Django 4.1.5 on 2023-01-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_alter_user_foto_alter_user_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Foto',
            field=models.ImageField(default=None, upload_to='profile', verbose_name='Imagem do perfil'),
        ),
    ]
