# Generated by Django 4.1.5 on 2023-01-05 12:42

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_alter_user_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagem',
            field=stdimage.models.JPEGField(default='profile', force_min_size=False, upload_to='profile', variations={'thumbnail': (200, 200)}, verbose_name='Foto de Perfil'),
        ),
    ]
