# Generated by Django 4.1.5 on 2023-01-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_alter_user_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imagem',
        ),
    ]
