# Generated by Django 4.1.5 on 2023-01-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0030_alter_election_n_eleicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generated_Election',
            fields=[
                ('N_Eleicao', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Titulo', models.CharField(max_length=30)),
                ('Data', models.DateField()),
                ('Descricao', models.CharField(max_length=150, null=True)),
                ('Ativo', models.BooleanField()),
                ('Disponibilizar', models.BooleanField()),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
