# Generated by Django 4.1.5 on 2023-01-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0032_alter_activity_user_participacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generated_election',
            name='Data',
            field=models.DateField(null=True),
        ),
    ]
