# Generated by Django 4.1.5 on 2023-01-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0038_alter_activity_user_participacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_election',
            name='N_Candidato',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
