# Generated by Django 4.1.5 on 2023-01-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0039_data_election_n_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_election',
            name='Candidatos',
            field=models.CharField(max_length=50),
        ),
    ]
