# Generated by Django 4.1.5 on 2023-01-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0040_alter_data_election_candidatos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity_User',
        ),
    ]
