# Generated by Django 4.1.5 on 2023-01-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0041_delete_activity_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_report',
            old_name='Balao',
            new_name='balao',
        ),
        migrations.RenameField(
            model_name='activity_report',
            old_name='Titulo',
            new_name='mome',
        ),
        migrations.RemoveField(
            model_name='activity_report',
            name='ID_REPORT',
        ),
        migrations.RemoveField(
            model_name='activity_report',
            name='Imagem',
        ),
        migrations.RemoveField(
            model_name='activity_report',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='activity_report',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='activity_report',
            name='sobrenome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity_report',
            name='titulo',
            field=models.CharField(choices=[('1', 'Problema com uma eleição'), ('2', 'Problema com Site'), ('3', 'Problema com conta')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
