# Generated by Django 4.1.5 on 2023-01-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0044_remove_activity_report_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='Disponibilizar',
        ),
    ]
